<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Dapper" />
        <PackageReference Include="MassTransit" />
        <PackageReference Include="Newtonsoft.Json" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Application\BuildingBlocks.Application.csproj" />
        <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.IntegrationEvents\BuildingBlocks.IntegrationEvents.csproj" />
        <ProjectReference Include="..\Telemetry.Domain\Telemetry.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Telemetry.Application.UnitTests" />
    </ItemGroup>

</Project>
