<Project Sdk="Microsoft.NET.Sdk.Web">
	
	<ItemGroup>
		<ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.GrpcContracts\BuildingBlocks.GrpcContracts.csproj" />
		<ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Presentation\BuildingBlocks.Presentation.csproj" />
		<ProjectReference Include="..\ControlService.Application\Control.Application.csproj" />
		<ProjectReference Include="..\ControlService.Infrastructure\Control.Infrastructure.csproj" />
	</ItemGroup>

</Project>
