<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="AspNetCore.HealthChecks.NpgSql" />
        <PackageReference Include="DotNetEnv" />
        <PackageReference Include="EFCore.NamingConventions" />
        <PackageReference Include="Dapper" />
        <PackageReference Include="MassTransit.RabbitMQ" />
        <PackageReference Include="AspNetCore.HealthChecks.Rabbitmq" />
        <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
        <PackageReference Include="Quartz.Extensions.Hosting" />
        <PackageReference Include="ZiggyCreatures.FusionCache" />
        <PackageReference Include="ZiggyCreatures.FusionCache.Serialization.SystemTextJson" />
        <PackageReference Include="ZiggyCreatures.FusionCache.Backplane.StackExchangeRedis" />
        <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\BuildingBlocks.Domain\BuildingBlocks.Domain.csproj" />
        <ProjectReference Include="..\BuildingBlocks.Presentation\BuildingBlocks.Presentation.csproj" />
    </ItemGroup>
    
</Project>
