<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Identity.Core" />
        <PackageReference Include="Microsoft.Extensions.Identity.Stores" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Domain\BuildingBlocks.Domain.csproj" />
        <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.GrpcContracts\BuildingBlocks.GrpcContracts.csproj" />
    </ItemGroup>

</Project>
